version: '2'

services:
    go-api-gateway:
        build: docker/golang
        volumes:
            - ./src/gateway:/go/src/app
        command: go run main.go
        ports: 
            - '3000:3001'
        environment:
            PORT: "3001"
        networks:
            - backend
            - frontend

    go-api-posts:
        build: docker/golang
        volumes:
            - ./src/posts:/go/src/app
        command: go run main.go
        ports: 
            - '80:80'
        environment:
            PORT: "80"
            SERVICE_NAME: posts
            CONTAINER_URL: http://go-api-posts:80
            API_GATEWAY: http://go-api-gateway:3001/server-register
        networks:
            - backend
        depends_on:
            - "go-api-gateway"

    
    go-api-comments:
        build: docker/golang
        volumes:
            - ./src/comments:/go/src/app
        command: go run main.go
        ports: 
            - '80:80'
        environment:
            PORT: "80"
            SERVICE_NAME: comments
            CONTAINER_URL: http://go-api-comments:80
            API_GATEWAY: http://go-api-gateway:3001/server-register
        networks:
            - backend
        depends_on:
            - "go-api-gateway"

networks:
  frontend:
    internal: false
  backend:
    internal: true